import { notificationsMock } from "@/constants";
import { Container } from "@/shared";
import { Footer, Nav, Notifications } from "@/widgets";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => (
	<html lang="en">
		<body className={twMerge(inter.className, "bg-white dark:bg-slate-700")}>
			<Providers>
				<div className="min-h-screen flex flex-col py-2">
					<Nav />
					<main className="my-6">
						<Container>{children}</Container>
					</main>
					<Footer />
				</div>
				<Notifications data={notificationsMock} />
			</Providers>
			<Analytics />
			<SpeedInsights />
		</body>
	</html>
);

export default RootLayout;
